#!/usr/bin/env bash

# slightly scuffed wallpaper picker menu for use with pywal - uses nsxiv if installed, otherwise uses dmenu

FOLDER=~/Pictures/wallpapers # wallpaper folder (set this)
SCRIPT=~/scripts/pywal16 # script to run after wal for refreshing programs, etc.


menu () {
		if command -v nsxiv >/dev/null; then 
				CHOICE=$(nsxiv -otb $FOLDER/*)
		else 
				CHOICE=$(echo -e "Random\n$(command ls -v $FOLDER/*)" | dmenu -l 15 -i -p "Wallpaper: ")
		fi

case $CHOICE in
		Random) XDG_CURRENT_DESKTOP=i3 wal -i "$FOLDER" -o $SCRIPT ;; # dmenu random option
		*.*) XDG_CURRENT_DESKTOP=i3 wal -i "$CHOICE" -o $SCRIPT ;;
		*) exit 0 ;;
esac
}

# If given arguments:
# First argument will be used by pywal as wallpaper/dir path
# Second will be used as theme (use wal --theme to view built-in themes)

case "$#" in
		0) menu ;;
		1) XDG_CURRENT_DESKTOP=i3 wal -i "$1" -o $SCRIPT ;;
		2) XDG_CURRENT_DESKTOP=i3 wal -i "$1" --theme $2 -o $SCRIPT ;;
		*) exit 0 ;;
esac
